#!/usr/bin/env python3
"""Build review-only country blocking candidates from external and local evidence.

No candidate generated by this script is referenced by nginx.conf. A country is
activated only after it is added to BLOCK_COUNTRIES in build_final_policy.py and
the normal deployment bundle is rebuilt.
"""

from __future__ import annotations

import csv
import html
import ipaddress
import json
import re
from collections import Counter
from datetime import datetime
from pathlib import Path

import requests

try:
    from . import build_consolidated_report as consolidated
    from . import build_final_policy as policy
    from . import ip_shield_analyzer as analyzer
    from .paths import ALLOWLIST_FILE, BLACKLIST_FILE, DATA_DIR, LOG_DIR, OUTPUT_DIR
except ImportError:
    import build_consolidated_report as consolidated
    import build_final_policy as policy
    import ip_shield_analyzer as analyzer
    from paths import ALLOWLIST_FILE, BLACKLIST_FILE, DATA_DIR, LOG_DIR, OUTPUT_DIR


CONFIRM_WHOLE_COUNTRY = {"SC", "LT", "SE", "ID", "BR"}
ASN_ONLY = {"NL", "DE", "GB", "VN", "PL", "RO"}
ACTIVE_ALREADY = {"SG", "RU"}

DECISION_LABELS = {
    "confirm": "建议询问后整国封禁",
    "asn": "不整国封，改按ASN",
    "active": "已在当前策略启用",
    "observe": "证据不足，继续观察",
}


def collapse(networks):
    return list(ipaddress.collapse_addresses(networks))


def intersect_networks(left, right):
    left_ranges = sorted(
        (int(net.network_address), int(net.broadcast_address))
        for net in collapse(left) if net.version == 4
    )
    right_ranges = sorted(
        (int(net.network_address), int(net.broadcast_address))
        for net in collapse(right) if net.version == 4
    )
    output = []
    i = j = 0
    while i < len(left_ranges) and j < len(right_ranges):
        start = max(left_ranges[i][0], right_ranges[j][0])
        end = min(left_ranges[i][1], right_ranges[j][1])
        if start <= end:
            output.extend(policy.range_to_cidrs(start, end))
        if left_ranges[i][1] < right_ranges[j][1]:
            i += 1
        else:
            j += 1
    return collapse(output)


def parse_zone(text: str):
    result = []
    for line in text.splitlines():
        value = line.strip()
        if not value or value.startswith("#"):
            continue
        try:
            network = ipaddress.ip_network(value, strict=False)
        except ValueError:
            continue
        if network.version == 4:
            result.append(network)
    return collapse(result)


def download_ipdeny(data_dir: Path, country: str):
    target_dir = data_dir / "ipdeny"
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / f"{country.lower()}.zone"
    if not target.exists():
        url = (
            "https://www.ipdeny.com/ipblocks/data/countries/"
            f"{country.lower()}.zone"
        )
        response = requests.get(
            url,
            timeout=(15, 60),
            headers={"User-Agent": analyzer.UA},
        )
        response.raise_for_status()
        target.write_bytes(response.content)
    return parse_zone(target.read_text(encoding="utf-8", errors="replace"))


def protected_signal(item: analyzer.IPStats, verdict: analyzer.Verdict) -> bool:
    return bool(
        (verdict.trusted_bot and not policy.intentionally_blocked_bot(verdict))
        or policy.strong_human_or_ai(item)
        or (
            set(item.bot_claims).intersection(policy.CLAIM_PROTECTED_BOTS)
            and not policy.hard_bad(item)
        )
    )


def request_has_ip_exception(request: dict[str, object]) -> bool:
    ua = str(request["ua"])
    bot = analyzer.identify_bot(ua)
    if bot and bot[0] in policy.CLAIM_PROTECTED_BOTS:
        return True
    host = analyzer.referrer_host(str(request["referrer"]))
    browser_like = bool(re.search(
        r"Mozilla/5\.0|SamanthaDoubao|BytedanceWebview|MicroMessenger|Quark",
        ua,
        re.I,
    ))
    return analyzer.is_good_referrer(host) and browser_like


def table(headers, rows):
    head = "".join(f"<th>{html.escape(str(value))}</th>" for value in headers)
    body = "".join(
        "<tr>" + "".join(
            f"<td>{value if isinstance(value, str) and value.startswith('<') else html.escape(str(value))}</td>"
            for value in row
        ) + "</tr>"
        for row in rows
    )
    return f"<div class=scroll><table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>"


def main() -> None:
    root = Path(__file__).resolve().parent
    data_dir = DATA_DIR
    deploy = OUTPUT_DIR / "deploy"
    candidate_dir = deploy / "region_candidates"
    candidate_dir.mkdir(parents=True, exist_ok=True)

    evidence = json.loads(
        (root / "external_region_evidence.json").read_text(encoding="utf-8")
    )
    logs = analyzer.iter_log_files(LOG_DIR)
    stats, meta, _ = analyzer.parse_logs(logs)
    intel = analyzer.Intelligence(data_dir)
    intel.refresh_official_ranges(False)
    intel.refresh_dbip(False)
    intel.verify_ptr_claims(analyzer.ptr_jobs(stats), False)
    old_rules, invalid = analyzer.parse_blacklist(BLACKLIST_FILE)
    if invalid:
        raise RuntimeError("existing blacklist contains invalid lines")
    old_networks = [network for _, network in old_rules]
    allow_networks, _ = analyzer.parse_allowlist(ALLOWLIST_FILE)
    verdicts = {
        ip: analyzer.score_ip(item, intel, len(meta["daily"]), old_networks, allow_networks)
        for ip, item in stats.items()
    }
    current_black = consolidated.read_matcher(deploy / "black_ip.conf")
    current_trusted = consolidated.read_matcher(deploy / "trusted_ip.conf")

    country_items = {}
    for ip, item in stats.items():
        country_items.setdefault(verdicts[ip].geo.country or "ZZ", []).append(item)
    requests = list(policy.iter_requests(logs))

    rows = []
    output = {}
    combined_preview = []
    for country, external in evidence["countries"].items():
        items = country_items.get(country, [])
        dbip = policy.db_networks(intel.country, {country})
        ipdeny = download_ipdeny(data_dir, country)
        agreed_raw = intersect_networks(dbip, ipdeny)

        observed_exclusions = []
        for item in items:
            if protected_signal(item, verdicts[item.ip]):
                observed_exclusions.append(ipaddress.ip_network(item.ip))
        agreed_deployable = policy.subtract_networks(
            agreed_raw,
            observed_exclusions,
        )
        matcher = policy.IPv4Matcher(agreed_deployable)

        incremental_requests = 0
        incremental_ips = set()
        for request in requests:
            ip = str(request["ip"])
            if not matcher.contains(ip) or current_trusted.contains(ip):
                continue
            if request_has_ip_exception(request):
                continue
            if not consolidated.request_blocked(request, current_black, current_trusted):
                incremental_requests += 1
                incremental_ips.add(ip)

        local_requests = sum(item.requests for item in items)
        protected_ips = sum(
            protected_signal(item, verdicts[item.ip]) for item in items
        )
        high_risk_ips = sum(
            verdicts[item.ip].level == "建议封禁" for item in items
        )
        hard_bad_ips = sum(policy.hard_bad(item) for item in items)
        search_ips = sum("search" in item.bot_kinds for item in items)
        ai_ips = sum(
            any(kind.startswith("ai_") for kind in item.bot_kinds)
            for item in items
        )
        repeated = sum(len(item.days) >= 3 for item in items)
        dbip_addresses = sum(net.num_addresses for net in dbip)
        agreed_addresses = sum(net.num_addresses for net in agreed_raw)
        agreement = agreed_addresses / dbip_addresses if dbip_addresses else 0

        if country in ACTIVE_ALREADY:
            decision = "active"
        elif country in CONFIRM_WHOLE_COUNTRY:
            decision = "confirm"
            combined_preview.extend(agreed_deployable)
        elif country in ASN_ONLY:
            decision = "asn"
        else:
            decision = "observe"

        row = {
            "country": country,
            "name_zh": external["name_zh"],
            "decision": decision,
            "audience_relevance": external["audience_relevance"],
            "external_summary": external["external_summary"],
            "spamhaus_rank": external.get("spamhaus_rank"),
            "spamhaus_c2": external.get("spamhaus_c2"),
            "cloudflare_rank": external.get("cloudflare_rank"),
            "local_ips": len(items),
            "local_requests": local_requests,
            "high_risk_ips": high_risk_ips,
            "hard_bad_ips": hard_bad_ips,
            "protected_ips": protected_ips,
            "search_ips": search_ips,
            "ai_ips": ai_ips,
            "repeat_3day_ips": repeated,
            "incremental_requests": incremental_requests,
            "incremental_ips": len(incremental_ips),
            "dbip_cidrs": len(collapse(dbip)),
            "agreed_cidrs": len(agreed_raw),
            "deployable_cidrs": len(agreed_deployable),
            "dbip_addresses": dbip_addresses,
            "agreed_addresses": agreed_addresses,
            "agreement_ratio": round(agreement, 4),
        }
        output[country] = row
        rows.append(row)

        lines = [
            "# REVIEW ONLY - not referenced by nginx.conf",
            f"# {country} {external['name_zh']} - {DECISION_LABELS[decision]}",
            "# CIDRs are the IPv4 intersection of DB-IP Lite 2026-07 and IPdeny;",
            "# observed search/AI/human-signal /32 addresses have been excluded.",
            f"# DB-IP/IPdeny address agreement: {agreement:.1%}",
        ]
        lines.extend(
            f"{network} 1;"
            for network in sorted(
                agreed_deployable,
                key=lambda net: (int(net.network_address), net.prefixlen),
            )
        )
        (candidate_dir / f"{country.lower()}_review_only.conf").write_text(
            "\n".join(lines) + "\n",
            encoding="utf-8",
        )

    combined_preview = collapse(combined_preview)
    combined_lines = [
        "# REVIEW ONLY - DO NOT INCLUDE BEFORE USER CONFIRMATION",
        "# Proposed whole-country candidates: SC LT SE ID BR",
        "# Generated from DB-IP/IPdeny intersections with observed protection holes.",
    ]
    combined_lines.extend(
        f"{network} 1;"
        for network in sorted(
            combined_preview,
            key=lambda net: (int(net.network_address), net.prefixlen),
        )
    )
    (candidate_dir / "PROPOSED_COUNTRIES_NOT_ACTIVE.conf").write_text(
        "\n".join(combined_lines) + "\n",
        encoding="utf-8",
    )

    rows.sort(
        key=lambda row: (
            {"active": 3, "confirm": 2, "asn": 1, "observe": 0}[row["decision"]],
            row["incremental_requests"],
            row["local_requests"],
        ),
        reverse=True,
    )
    payload = {
        "generated_at": datetime.now().astimezone().isoformat(),
        "sample": {
            "requests": meta["parsed"],
            "unique_ips": len(stats),
            "days": sorted(meta["daily"]),
            "limitation": "近期manbohub日志，不代表全网；外部情报只建立候选池。",
        },
        "method": {
            "location": "DB-IP Lite 2026-07 与 IPdeny 2026-06/07 IPv4 CIDR取交集",
            "protection": "排除本窗口搜索/AI/真人信号IP；Nginx运行时继续保留搜索/AI UA和Referer例外",
            "activation": "本报告和候选conf均不被nginx.conf引用，必须确认后重建正式策略",
        },
        "countries": rows,
        "proposed": sorted(CONFIRM_WHOLE_COUNTRY),
        "active": sorted(ACTIVE_ALREADY),
        "asn_only": sorted(ASN_ONLY),
        "sources": evidence["sources"],
    }
    (candidate_dir / "region_candidate_policy.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    with (candidate_dir / "region_candidate_policy.csv").open(
        "w",
        encoding="utf-8-sig",
        newline="",
    ) as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

    table_rows = []
    for row in rows:
        evidence_link = (
            f"<span title=\"{html.escape(row['external_summary'])}\">"
            f"S:{row['spamhaus_rank'] or '-'} / C:{row['cloudflare_rank'] or '-'}</span>"
        )
        table_rows.append([
            f"{row['name_zh']} ({row['country']})",
            DECISION_LABELS[row["decision"]],
            row["audience_relevance"],
            evidence_link,
            row["local_ips"],
            row["local_requests"],
            row["hard_bad_ips"],
            row["protected_ips"],
            f"{row['search_ips']}/{row['ai_ips']}",
            row["incremental_requests"],
            row["incremental_ips"],
            f"{row['agreement_ratio']:.1%}",
            row["deployable_cidrs"],
        ])

    proposed_rows = [
        row for row in table_rows
        if any(f"({country})" in str(row[0]) for country in CONFIRM_WHOLE_COUNTRY)
    ]
    report = f"""<!doctype html><html lang=zh-CN><head><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<title>整国/地区封禁候选确认报告</title><style>
body{{margin:0;background:#f4f7fb;color:#172033;font:14px/1.65 system-ui,"Microsoft YaHei",sans-serif}}
main{{max-width:1380px;margin:auto;padding:24px}}.hero{{color:#fff;background:linear-gradient(135deg,#312e81,#2563eb);padding:25px;border-radius:14px}}
section{{background:#fff;border:1px solid #e4e9f1;border-radius:12px;padding:18px;margin:14px 0}}
.warn{{border-left:4px solid #f79009;background:#fffaeb;padding:11px}}.good{{border-left:4px solid #12b76a;background:#ecfdf3;padding:11px}}
.scroll{{overflow:auto}}table{{width:100%;border-collapse:collapse}}th,td{{padding:8px 10px;border-bottom:1px solid #e4e9f1;text-align:left;white-space:nowrap}}
th{{background:#f8fafc;position:sticky;top:0}}code{{font-family:Consolas,monospace}}a{{color:#175cd3}}
</style></head><body><main>
<div class=hero><h1>整国/地区封禁候选确认报告</h1>
<div>外部威胁情报 × 近期本站日志 × 双来源CIDR交集 · 仅供确认，尚未启用新国家</div></div>
<section><h2>需要你确认的五个候选</h2>
{table(['国家','建议','受众相关性','外部排名 S/C','本站IP','本站请求','硬攻击IP','保护IP','搜索/AI IP','预计新增拦截','新增IP','双库地址一致率','规则数'], proposed_rows)}
<p class=warn><strong>这些候选目前没有被 <code>nginx.conf</code> 引用。</strong>候选文件位于 <code>region_candidates/PROPOSED_COUNTRIES_NOT_ACTIVE.conf</code>，文件名和首行都明确标记为不可直接启用。</p>
</section>
<section><h2>完整候选池</h2>
{table(['国家','建议','受众相关性','外部排名 S/C','本站IP','本站请求','硬攻击IP','保护IP','搜索/AI IP','预计新增拦截','新增IP','双库地址一致率','规则数'], table_rows)}
<p>S=Spamhaus 2025下半年僵尸网络C&C位置排名；C=Cloudflare 2025Q2 DDoS来源排名。排名表示网络节点所在地，不表示攻击者国籍。</p>
</section>
<section><h2>我为什么这样分组</h2><ul>
<li><strong>塞舌尔：</strong>受众相关性极低，Spamhaus C&C位置第8且增长287%；本站当前没有流量，属于低现实误伤的预防性候选。</li>
<li><strong>立陶宛：</strong>本站22个IP产生699次请求，10个硬攻击IP；外部报告显示当地相关注册商滥用增长明显。</li>
<li><strong>瑞典：</strong>本站60个IP、585次请求且没有保护信号；Spamhaus C&C位置第10。</li>
<li><strong>印度尼西亚：</strong>Cloudflare连续一年列为最大DDoS来源；但本站存在少量AI/真人信号，所以只建议确认，不自动启用。</li>
<li><strong>巴西：</strong>本站4,013次请求且有14个硬攻击IP，受众相关性低；部分流量已被ASN策略覆盖，表中“新增拦截”才是真正增益。</li>
<li><strong>荷兰、德国、英国、越南、波兰、罗马尼亚：</strong>外部滥用明显，但本站搜索/AI/真人或云基础设施信号较多，整国误伤不划算，优先按ASN。</li>
</ul></section>
<section><h2>定位精度与局限</h2>
<p>候选CIDR不是简单相信一个数据库：脚本取 DB-IP Lite 2026-07 地理范围与 IPdeny 最新国家CIDR的<strong>交集</strong>，只封两边都认为属于该国的IPv4，并再次减去本窗口保护IP。交集会牺牲覆盖率，但比并集更适合封禁。</p>
<p class=warn>IP地理定位永远不可能100%准确，尤其是VPN、移动网络、Anycast和跨国云。城市级定位远弱于国家级，因此本轮没有新增任何城市封禁。</p>
</section>
<section><h2>来源</h2><ul>
<li><a href="{evidence['sources']['spamhaus_h2_2025']['url']}">Spamhaus Botnet Threat Update Jul-Dec 2025</a></li>
<li><a href="{evidence['sources']['cloudflare_q2_2025']['url']}">Cloudflare 2025 Q2 DDoS Threat Report</a></li>
<li><a href="{evidence['sources']['cloudflare_q3_2025']['url']}">Cloudflare 2025 Q3 DDoS Threat Report</a></li>
<li><a href="{evidence['sources']['dbip_lite']['url']}">DB-IP Lite</a> · <a href="{evidence['sources']['ipdeny']['url']}">IPdeny CIDR zones</a></li>
</ul></section>
</main></body></html>"""
    (deploy / "REGION_BLOCK_CONFIRMATION.html").write_text(report, encoding="utf-8")
    # Keep the user's currently-open regional report path current.
    (deploy / "regional_risk_report.html").write_text(report, encoding="utf-8")
    print(json.dumps(payload, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
